### PR TITLE
[42] Publish

### PR DESCRIPTION
**Pull request by BasThomas**
Reviews are welcome 😃 @jessesquires @modocache @jpsim

### CODE REVIEW

**Comment by jpsim** [comment]
> And as a reminder, Chris Lattner explained what's in store for Swift 4 and its release plan.

I'd add "back in July" to the end of that sentence. Since this is Swift Weekly, I first thought a new post had come in in the last week and I had missed it 😄.

> As Brian Gesiak mentioned in issue #39, source-breaking really are hard to determine.

"... source-breaking _changes_ are ..." (missing the word "changes").

---

I couldn't find any other typos or issues. Well done! 👏

**Comment by jessesquires** [comment]
LGTM

**Comment by jessesquires** [comment]
👏 thanks @BasThomas ! 🎉

**Comment by BasThomas** [comment]
Thank *you*, @jessesquires 🙌

**Pull request merged**
