### PR TITLE
Time travel back from future

### PR DESCRIPTION
**Pull request by tomquist**
Hopefully one day Apple will make all our lives more easy: http://www.openradar.me/radar?id=4949404398125056

### CODE REVIEW

**Comment by BasThomas** [comment]
cc @terhechte 😂

**Comment by terhechte** [comment]
Hahaha, These mistakes keep on happening until Apple finally resolves my bug report :)

@tomquist when are you coming back to Hamburg? ;)

**Comment by tomquist** [comment]
@terhechte when your radar is fixed ;-)

**Comment by terhechte** [comment]
@timcook you readin‘ this?

**Comment by TimCook** [comment]
Hahaha! I love Apple developer humor!

**Comment by jessesquires** [comment]
Ha. Thanks @tomquist ! 😄 

lol @TimCook

**Pull request merged**
