### PR TITLE
[38] Add intro

### PR DESCRIPTION
**Pull request by BasThomas**

### CODE REVIEW

**Comment by jessesquires** [comment]
We should let @jpsim handle this one 😊

**Comment by BasThomas** [comment]
👍

**Comment by jpsim** [comment]
Thanks for fleshing this out @BasThomas! I'll no doubt borrow some of your ideas in the intro I'm writing now.

Thanks to you and @modocache for helping so much with issue 38!

**Comment by BasThomas** [comment]
🙌

**Pull request closed without merging**
