### PR TITLE
Hyper links

### PR DESCRIPTION
**Pull request by eejahromi**
Added markdown codes to every link included in weekly issues 0-10 (and Issue 11 draft) in order to open links in a new tab to prevent from leaving the page or the user having to open it specifically in another tab!
SwiftWeekly Rocks!!

Cheers!

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @eejahromi ! :smile: :tada: :+1:  

This is awesome! I didn't know this was possible.

img

img

**Comment by ole** [comment]
Although this has already been merged, I’d like to provide some arguments why I don’t like this change and why I generally think opening links in new tabs is a bad choice for most websites:

1. Opening links in new tabs breaks the back button, which is arguably the best user interface element of the web. Everybody understands how it works. (Admittedly, given the audience of this site we can expect readers to be very proficient web navigators so this may not be a huge deal.)

2. If links open in the same tab by default, this can easily be overridden in all browsers (Cmd+Click on the desktop, long press on mobile). The reverse, overriding a link with `target="_blank"` to open in the same tab, is impossible in Safari on iPhone (and also on OS X, I believe).

3. Having a link create a new tab is a very jarring experience in Safari on the iPhone (arguably, one of your most important platforms). It takes two taps and a swipe gesture to close the new tab and go back to the original one. This sucks and is much more effort than just swiping back.

Maybe I don’t understand why some (many?) people actually prefer links to open in new tabs, but I seriously don’t see the benefit. To me, it would only make sense if the new tab would open _behing the current tab_ so that I could open several links from one page without having to switch back to it every single time, then close that page and read the new tabs one by one. Again, Mobile Safari doesn't behave that way and neither do most desktop browsers, so I need to long press/Cmd+Click anyway to get the intended behavior.

If someone could enlighten to me why they consider links that open in new tabs an improvement, I’d love to learn how you are using your browsers.

**Comment by jessesquires** [comment]
Thanks @ole ! :heart_eyes_cat: 

Those are really strong points — and now, I think I actually agree that this should be reverted. :grin: 
Especially for newsletters, this is typically the behavior that *I prefer* — but I think the usability arguments here trump that.

-----------

@eejahromi —still, huge thanks for this idea and teaching me something I didn't know! :smile:

**Comment by jessesquires** [comment]
Also, markdown stays much cleaner without this -- which is also a huge win, IMO.

**Comment by eejahromi** [comment]
I think these are valid points.

For whatever reason I've been always reading Swift Weekly Brief on my laptop. Probably because I usually check out all the links and sometimes I wanna check some GitHub repo so I go in deeper and it gets messy finding my way back.

I've only read one of them on my iPhone. On twitter's webView it's just a normal browser (no page stacks) but the only time I read it on my iPhone was in Safari which I use 3dTouch 😜😂 to glance at the links.

Cheers guys!

**Pull request merged**
