### PR TITLE
Issue 95

### PR DESCRIPTION
**Pull request by modocache**

### CODE REVIEW

**Comment by BasThomas** [comment]
We can remove the draft right?

**Comment by modocache** [comment]
Weird, I must have messed up the commit somehow. I definitely ran `mv _drafts/blah-blah.md _posts/blah-blah.md`. Maybe I accidentally saved the old file and included it in the commit... my bad! Yes I'll remove the draft.

**Comment by modocache** [comment]
https://github.com/SwiftWeekly/swiftweekly.github.io/pull/337

**Comment by jessesquires** [comment]
Thanks @modocache and @BasThomas !

🙌

**Pull request merged**
