### PR TITLE
Issue 186

### LINKED ISSUE #645: [186] Issue #186 - June 03, 2021
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/main/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/main/_drafts). If you want to contribute directly, feel free to [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

### PR DESCRIPTION
**Pull request by fassko**
Closes #645

### CODE REVIEW

**Review by jeroenleenarts — DISMISSED** [review]
Proposals in review repeats the exact same paragraph 3 times, refering to the concurrency feature. Is this correct?

**Comment by jeroenleenarts** [comment]
Still some work left on the body of the newsletter. 4 TODOs. :)

**Comment by fassko** [comment]
@jeroenleenarts sorry forgot to push my changes :)

**Review by jeroenleenarts — APPROVED** [review]

**Review by jeroenleenarts — DISMISSED** [review]

**Review by JaredHalpern — DISMISSED** [review]
I made some small tweaks, directly to the file. LGTM

**Review by morqon — DISMISSED** [review]
Added my usual copy edits to [this branch](https://github.com/SwiftWeekly/swiftweekly.github.io/pull/648), now merged. 

**Important**: We have one missing link, marked as a TODO

```
### Commits and pull requests
 
* [Andrew Trick](https://github.com/atrick) made [a pull request](TODO) which fixes correctness bugs that are blocking other optimisation bug fixes.
```

Hopefully someone has time to find that 🤞🏻 

Thanks!

**Comment by fassko** [comment]
Thank you, everyone, for your help! :)

**Pull request merged**
