### PR TITLE
Initial dark mode

### LINKED ISSUE #461: Offer a dark theme of the website

### PR DESCRIPTION
**Pull request by BasThomas**
Fixes #461

To do:

- [x] Increase contrast / make issue numbers bold on homepage
- [x] Change code block (`pre`?) background for dark mode
- [ ] (Optional) look into supporting darker buttons / search field

Please share your thoughts; see the images below.

There's one thing I can't seem to wrap my head around, which is the (what I think is) `pre`; I want its background to be `var(--codeblock-background);` but I can't seem to get that to work using the following:

```css
pre {
   background-color: var(--codeblock-background);
}
```

Any ideas?

I also haven't yet looked into the buttons / search bar.

Any other feedback, tips, or code-cleanup ideas are more than welcome!

image

image

### CODE REVIEW

**Comment by jessesquires** [comment]
wow that's cool. looks great!

CSS has native `var`s? TIL

**Comment by jessesquires** [comment]
not completely sure about `pre` -- i'm assuming you've peeked around in your browser's console?

**Comment by BasThomas** [comment]
> not completely sure about `pre` -- i'm assuming you've peeked around in your browser's console?

Yep, and got a hint from someone to add `!important`... that fixed it 😀

**Comment by BasThomas** [comment]
Let's take it from here :)

**Pull request merged**
