### PR TITLE
Fix one more typo

### PR DESCRIPTION
**Pull request by ole**
Linking to pull requests with typo fixes on Twitter helps because then other people see them and find more typos in the same paragraph.

### CODE REVIEW

**Comment by BasThomas** [comment]
🙌

**Comment by BasThomas** [comment]
These diffs are not very helpful though...
😡 GitHub
img_0643

**Comment by ole** [comment]
Yeah, sometimes GitHub just doesn't highlight the changed word. No idea what triggers that.

**Comment by jessesquires** [comment]
ugh. I'm failing! It just took me 10 min to find the error. s/required/require 🤦‍♂️ 

Thanks so much @ole ! 💯

**Pull request merged**
