### PR TITLE
[Translation] Portuguese (pt-BR)

### PR DESCRIPTION
**Pull request by rafaelcsa**
Hi @jessesquires,

It took me a while, but finally the first issue is now translated. I intend to do the other ones in a much quicker (more swifty? :stuck_out_tongue_winking_eye:) fashion, hopefully.

Let me know if you see any issues!

### CODE REVIEW

**Comment by jessesquires** [comment]
Awesome! :tada: thanks @rafaelcsa !

It looks like there are a bunch of unrelated commits here. Can you rebase on master and squash into a single commit?

**Comment by rafaelcsa** [comment]
Just did the rebase + squash. Hope I got it right. :smile:  I don't have a lot of practice with pull requests yet.

**Comment by jessesquires** [comment]
No worries! :smile: 

Looks like there are still some unwanted changes:
https://github.com/SwiftWeekly/swiftweekly.github.io/pull/24/files

This is probably fastest and easiest: :smile: 

1. Copy your translated issues 
* Make a fresh fork of the repo
* Re-add the issues and commit
* Submit PR

**Comment by jessesquires** [comment]
Hey @rafaelcsa :smile: any updates here?

**Pull request closed without merging**
