### PR TITLE
Publish issue 71

### PR DESCRIPTION
**Pull request by BasThomas**

### CODE REVIEW

**Comment by BasThomas** [comment]
Ping @jessesquires, did you mean to publish before? As you closed the issue and made a new one for next week, but you didn't put issue 71 in `_posts`. Also take a look at #263 before merging this one :)

**Comment by BasThomas** [comment]
Ooh, changing the post to the `_posts` directory doesn't confuse Travis / Danger anymore! 🎉

**Comment by jessesquires** [comment]
thanks @BasThomas !

lol -- time zones. that was all late wednesday night for me. now it's thursday morning. 😊 

just published the issue before opening github!

**Comment by jessesquires** [comment]
thanks though! 🙌

**Pull request closed without merging**
