### PR TITLE
Issue #179 draft

### LINKED ISSUE #595: [179] Issue #179 - February 25, 2021
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/main/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/main/_drafts). If you want to contribute directly, feel free to [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

### PR DESCRIPTION
**Pull request by fassko**
Closes #595

### CODE REVIEW

**Comment by JaredHalpern** [comment]
I've added my suggested updates in a separate PR this week instead of directly editing the file. Let me know if that works. I feel more comfortable doing it this way rather than directly editing a file. :)

**Comment by morqon** [comment]
> @fassko I've added my suggested updates in a separate PR this week instead of directly editing the file.

I'll add my changes to your PR @JaredHalpern, if that's ok. Then all copy edits can be merged in a single step.

**Review by JaredHalpern — APPROVED** [review]
LGTM.

**Review by morqon — APPROVED** [review]
Copy edits and a quick scan of the link list, and looks good 👍🏻

**Comment by fassko** [comment]
Thank you @JaredHalpern and @morqon! 🙏
I'm so happy to have you both.

**Comment by JaredHalpern** [comment]
Happy to help :)

**Comment by morqon** [comment]
A pleasure!

**Pull request merged**
