### PR TITLE
[38] Add ClangImporter refactor

### PR DESCRIPTION
**Pull request by BasThomas**

### CODE REVIEW

**Comment by jessesquires** [comment]
@BasThomas conflicts. sorry 😄

**Comment by jessesquires** [comment]
@BasThomas feel free to merge on your own once conflicts are fixed 😄

**Comment by BasThomas** [comment]
@jessesquires what's up with the Dangerfile here?

**Comment by jessesquires** [comment]
Ah, you mean "Please rebase to get rid of the merge commits in this PR" ?

Danger is setup to warn/error on merges (to prefer rebasing). I'll squash and merge on GH.

I guess I'll remove that from Danger. Not too important.

**Comment by BasThomas** [comment]
No, rather the CI run on the merge reporting Danger exiting with a 1.

**Pull request merged**
