### PR TITLE
Update multiline strings to HEREDOC in Danger

### PR DESCRIPTION
**Pull request by BasThomas**
I saw in the 104 issue that it was basically "leaking" a `<` that I could not complain; maybe this fixes it.

screen shot 2018-03-08 at 13 40 05

### CODE REVIEW

**Comment by jessesquires** [comment]
If this doesn't work, there's:

> **MESSAGING OPTIONS**
>
> Outputs markdown under the table:
> `markdown("## ")`

http://danger.systems/ruby/

Not sure if this is what we want though

**Comment by BasThomas** [comment]
Probably not, as that does not include the message in the table, omitting the useful ⚠️, making it easier to overlook. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
Actually, you know what'd be cool?

Can Danger comment *after* a PR is merged? 

If so, it would be nice to have her comment with steps 2,3,4

**Comment by SD10** [comment]
> Can Danger comment after a PR is merged?

It cannot, however, [peril](https://github.com/danger/peril) can. You can use peril for basically any GitHub event hook.

**Pull request merged**
