### PR TITLE
[Translation] French (fr)

### PR DESCRIPTION
**Pull request by havocked**
Alright as a proof of good faith, I did the first translation of Issue 0. It's starting to be a bit late now for me ^^. Will clean the writing tomorrow !

It's gonna take me a least 1 week 1/2 to catch up all the issues !

Cheers !

#13

### CODE REVIEW

**Comment by jessesquires** [comment]
Woo! :tada: Let me know when this is ready to merge.

>It's gonna take me a least 1 week 1/2 to catch up all the issues!

No worries! There's absolutely no pressure.

**Comment by havocked** [comment]
First draft of Issue 1 translated into FR :+1:.
Still need speel checking.

**Comment by jessesquires** [comment]
Awesome! :tada:

**Comment by jessesquires** [comment]
Hey @havocked !

Just wanted to check-in on this. I just pushed a new branch, [`french`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/french).

Let me know when you are ready and we can merge everything there until #12 is done. :+1:

**Comment by havocked** [comment]
Hey ! Ok perfect, i'll merge what I have this week. I'll still have some issues to catch up. But starting tomorrow i'll have more time to dedicate myself for this task :p

**Comment by jessesquires** [comment]
Hey @havocked :smile:  Just wanted to check in.

I should have time to work on the jekyll infrastructure this weekend. Hopefully we can start posting translations soon!

**Comment by jessesquires** [comment]
Hey @havocked :smile: — any updates here?

**Pull request closed without merging**
