### PR TITLE
[39] Update proposal list

### PR DESCRIPTION
**Pull request by BasThomas**
No proposals, although SE-0138 is still under review. It should have ended September 14 though, so please wait to merge to see if it will still be changing status before Thursday's post.

### CODE REVIEW

**Comment by modocache** [comment]
Why "DO NOT MERGE"?

**Comment by BasThomas** [comment]
> No proposals, although SE-0138 is still under review. It should have ended September 14 though, **so please wait to merge to see if it will still be changing status before Thursday's post**.

**Comment by BasThomas** [comment]
According to Erica Sadun, the proposal has been accepted. You can merge it now :)

**Comment by jessesquires** [comment]
>... although no `swift-evolution-announce` mail has been sent as of yet.

to:

>... although no `swift-evolution-announce` email was sent.

😄

**Comment by BasThomas** [comment]
... and apparently, a mail went out via `swift-evolution`. Updated.

**Comment by modocache** [comment]
Thanks! Looks like you'll need to rebase.

**Comment by modocache** [comment]
Oops, never mind, I don't know how to use all of GitHub's new, fancy features. I'll merge this.

**Pull request merged**
