### PR TITLE
Publish issue 40

### PR DESCRIPTION
**Pull request by modocache**
Final reviews, anyone?

Sorry for the short review window, but I'll merge this at 2PM ET (11AM PT).

### CODE REVIEW

**Comment by BasThomas** [comment]
What about #99?

**Comment by modocache** [comment]
Oops! Missed that one. I had one comment for you, then I'll merge it.

**Comment by modocache** [comment]
OK, merged your addition, @BasThomas.

**Comment by jessesquires** [comment]
🎉 🙌

**Pull request merged**
