### PR TITLE
Update 2016-03-03-issue-12.md

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
https://twitter.com/KostiaKoval/status/705316504250806272 :D

### CODE REVIEW

**Comment by jessesquires** [comment]
:tada:

**Comment by jessesquires** [comment]
thanks @aciidb0mb3r! :smile:

**Comment by aciidb0mb3r** [comment]
😎

On Friday 4 March 2016, Jesse Squires <notifications@github.com> wrote:

> thanks @aciidb0mb3r <https://github.com/aciidb0mb3r>! [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SwiftWeekly/swiftweekly.github.io/pull/22#issuecomment-192025659>
> .
>


-- 
Ankit

**Comment by kostiakoval** [comment]
👏👍😍🎉

**Pull request merged**
