### PR TITLE
Add Twitter card meta-tags

### PR DESCRIPTION
**Pull request by gregheo**
Adds additional meta tags for nicer Twitter cards. Should gain ~83% more Twitter engagement. Full spec here: https://dev.twitter.com/cards/types/summary

Second set of eyes & stamp appreciated.

ref #258

### CODE REVIEW

**Comment by BasThomas** [comment]
And if we *do* include the image, I suppose we should also add an alt as suggested by Twitter. 😃

**Comment by jessesquires** [comment]
@BasThomas RE: logo, in this case I think it's ok -- we don't have a specific image per issue. 😄

**Comment by jessesquires** [comment]
Thanks so much @gregheo ! 🙌 This is awesome. 😍 I think we're *almost* "friends" now. 😉

**Comment by BasThomas** [comment]
> @BasThomas RE: logo, in this case I think it's ok -- we don't have a specific image per issue. 😄

Yeah, that's what I was wondering. In that case, we might want to add a `twitter:image:alt` as well?

**Comment by BasThomas** [comment]
🤔, there seems to be [another](https://dev.twitter.com/cards/markup) interesting tag: `twitter:creator` (@username of content creator) which we might want to use as well?

**Comment by jessesquires** [comment]
@BasThomas -- both sound good to me!

**Comment by gregheo** [comment]
re using the same logo: I've always taken that as a suggestion ;)

You can test using the card validator (https://cards-dev.twitter.com/validator); I think the logo looks great!

**Comment by jessesquires** [comment]
beautiful! 🌮 🎉

**Pull request merged**
