### PR TITLE
Issue 183

### LINKED ISSUE #631: [183] Issue #183 - April 22, 2021
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/main/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/main/_drafts). If you want to contribute directly, feel free to [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

### PR DESCRIPTION
**Pull request by fassko**
Closes #631

### CODE REVIEW

**Review by jeroenleenarts — DISMISSED** [review]
Did a few minor tweaks, doubles spaces and such.

**Comment by jeroenleenarts** [comment]
@fassko Ready when this pull request is to send it out. :) Let's hope @JaredHalpern and @morqon have some time to do their review.

It is a good workflow to have so many eyes on the content before sending it. 👍

**Review by JaredHalpern — APPROVED** [review]
LGTM :)

**Review by jeroenleenarts — APPROVED** [review]

**Comment by morqon** [comment]
Adding some changes now, hope it's not too late! ☺️

**Comment by fassko** [comment]
@morqon No, right on time, thanks! :)

**Review by morqon — APPROVED** [review]
Made some very minor changes this week, to the intro text, and a few small fixes in the link list. Hope that helps!

**Comment by fassko** [comment]
Thank you @jeroenleenarts @JaredHalpern and @morqon ! :)

**Pull request merged**
