### PR TITLE
Fix speling erorrs

### PR DESCRIPTION
**Pull request by gregheo**
These spelling errors are either the most clever or the most egregious, so merge or decline as you see fit 😂

### CODE REVIEW

**Comment by BasThomas** [comment]
Thanks Mister!

**Comment by gregheo** [comment]
ahhh, didn't make it in time before the email went out ✉️🚀

**Comment by BasThomas** [comment]
😱

**Comment by jessesquires** [comment]
lol ugh. I'm terrible. 😅  I need to start opening PRs again. Thank you Mr. @gregheo 

Thanks @BasThomas for the quick merge! 🎉

**Pull request merged**
