### PR TITLE
[47] Publish

### LINKED ISSUE #126: [47] Issue #47, Nov 17th
Referencing tweet: https://twitter.com/jesse_squires/status/797518315048448000

Hey! I'd love to help out with the new issue.

### PR DESCRIPTION
**Pull request by BasThomas**
I removed the second example in `Finally`, as that didn't render correctly: 

screen shot 2016-11-17 at 09 36 33

This also closes #126

### CODE REVIEW

**Comment by BasThomas** [comment]
Want to review, @jessesquires @modocache @codeOfRobin?

Also, I can't merge this @jessesquires, as Travis doesn't like the file moving.

**Comment by jessesquires** [comment]
👍 I'll merge

**Comment by BasThomas** [comment]
Thanks!

**Comment by jessesquires** [comment]
thanks @BasThomas ! 👏

**Pull request merged**
