### PR TITLE
Fix typo in issue #161

### PR DESCRIPTION
**Pull request by MaxDesiatov**

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Apparently CI is failing because the danger action picks up my GitHub token, which doesn't have appropriate scopes, because I'm not a member of this org 🤔

**Comment by BasThomas** [comment]
Thanks!

**Comment by jessesquires** [comment]
> Apparently CI is failing because the danger action picks up my GitHub token, which doesn't have appropriate scopes, because I'm not a member of this org

Yeah... I've noticed this. Seems like a bug/limitation of GH Actions? 😭

**Comment by jessesquires** [comment]
Does anyone know the correct place to report a bug like that?

**Comment by MaxDesiatov** [comment]
As far as I understand, it's a security precaution (read "limitation"). Otherwise I'd be able to submit a PR against your GHA workflow with `echo {{ secrets.DANGER_GITHUB_API_TOKEN }}` to get your token logged. But currently if I do that, I'd only get my own token, or most probably an error about this secret not existing for my account. And even if that's my own token, it doesn't have enough permissions to post in your repo. Seems like the only way around is to create a separate bot account for these things.

**Comment by jessesquires** [comment]
@MaxDesiatov 

> Seems like the only way around is to create a separate bot account for these things.

Hm... so the token we use here **does** live on a bot account, then we added it to this repo's secrets.

Are you suggesting a different setup?

**Comment by MaxDesiatov** [comment]
I've actually tried that, doesn't make a difference for Danger. There are some actions where the bot account does help, but for fork PRs and Danger, in my experience, it doesn't.

**Pull request merged**
