### PR TITLE
Remove extraneous parens

### PR DESCRIPTION
**Pull request by gregheo**
MAKE LINKS GREAT AGAIN

### CODE REVIEW

**Comment by BasThomas** [comment]
🙌

**Comment by jessesquires** [comment]
facepalm

thank you @gregheo 💯 

at least one person is reading!

**Comment by gregheo** [comment]
You know I used to be an editor so I have extra spidey sense about punctuation. 

But mostly I wanted to get my name into the commit history 😈

**Comment by jessesquires** [comment]
This is what happens when I publish before coffee ☕️

**Pull request merged**
